import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import QueryTool_properties from "./QueryTool_properties";

/**
 * Overrides of ResourceBundle "QueryTool" for Locale "de".
 * @see QueryTool_properties#INSTANCE
 */
ResourceBundleUtil.override(QueryTool_properties, {
  Tab_QueryTool_title: "Recherche",
  Action_showQueryTool_text: "Recherche",
  conditionTitle: "Suchbedingung",
  column_status_title: "Status",
  column_doctype_title: "Dokumenttyp",
  column_id_title: "ID",
  column_title_title: "Titel",
  column_path_title: "Pfad",
  label_showInLibrary: "In der Bibliothek öffnen",
  label_undelete: "Wiederherstellen",
  folder_label: "Ordner",
  button_new: "Neue Bedingung hinzufügen",
  button_remove: "Bedingung entfernen",
  button_send: "Query absenden",
  checkbox_subtypes: "Abgeleitete Dokumenttypen miteinbeziehen",
  combo_loadcount_label: "Anzahl Datensätze:",
  REFERENCED: "Wird verlinkt (allg.)",
  REFERENCES: "Verlinkt auf",
  REFERENCED_BY: "Wird verlinkt von",
  BELOW: "Pfad",
  baseFolder: "Basis-Ordner der Seite",
  containsWideLink: "Verlinkt seitenüberfreifend",
  creationDate: "Erstellungsdatum",
  creator: "Ersteller",
  editor: "Bearbeiter",
  id: "Content Id",
  isDeleted: "Ist gelöscht",
  isCheckedIn: "Ist eingecheckt",
  isCheckedOut: "Ist ausgecheckt",
  isDocument: "Ist ein Dokument",
  isFolder: "Ist ein Ordner",
  isInProduction: "Ist in Produktion",
  isMoved: "Ist verschoben worden",
  isNew: "Ist neu",
  isPlaceApproved: "Ist freigegeben (Ort)",
  isRenamed: "Ist umbenannt worden",
  isToBeDeleted: "Soll gelöscht werden",
  isToBeWithdrawn: "Zum Zurückziehen markiert",
  isUndeleted: "Ist wiederhergestellt worden",
  lastParent: "Letzter Elternordner (vor Löschung)",
  modificationDate: "Änderungsdatum",
  modifier: "Ändernder",
  name: "Name",
  parent: "Elternordner",
  placeApprovalDate: "Freigabedatum (Ort)",
  placeApprover: "Freigebender (Ort)",
  publicationName: "Publikationsname",
  publicationParent: "Elternordner bei Publikation",
  publicationDate: "Publikationsdatum (Ort)",
  publisher: "Publizierender (Ort)",
  isPublished: "Ist publiziert (Ort)",
  versionApprovalDate: "Freigabedatum",
  versionApprover: "Freigebender",
  versionIsApproved: "Ist freigegeben",
  versionIsPublished: "Ist publiziert",
  versionPublicationDate: "Publikationsdatum",
  versionPublisher: "Publizierender",
  versionEditionDate: "Bearbeitungsdatum",
  CONTAINS: "enthält",
  NOT_CONTAINS: "enthält nicht",
  EQUAL: "ist gleich",
  NOT_EQUAL: "ist ungleich",
  LESS: "ist kleiner als",
  GREATER: "ist größer als",
  LESS_EQUAL: "ist kleiner gleich",
  GREATER_EQUAL: "ist größer gleich",
  EXISTS: "ist befüllt",
  NOT_EXISTS: "ist nicht befüllt",
  NOT_REFERENCES: "Verlinkt nicht auf",
  prod: "In Produktion",
  cout: "In Bearbeitung von",
  appr: "Freigegeben",
  publ: "Publiziert",
  del: "Gelöscht",
  label_me: "mir",
  button_page_prev: "Vorherige Seite",
  button_page_next: "Nächste Seite",
  page_label: "Seite 0/0 (Einträge: 0-0/0)",
  paging_label_items: "Einträge",
  paging_label_page: "Seite",
  button_save_csv: "Angezeigte Suchergebnisse exportieren - CSV",
  button_save: "Query-Konfiguration speichern",
  button_load: "Query-Konfiguration laden",
  dialog_save_title: "Query-Konfiguration speichern",
  textField_name_label: "Name des Settings-Dokumentes",
  button_dialog_save: "Speichern",
  dialog_load_title: "Query-Konfiguration laden",
  button_dialog_load: "Laden",
});
