packages:
  - apps/main/query-studio-plugin
catalog:
  '@coremedia/set-version': ^1.2.0
  '@coremedia/studio-client.app-context-models': 2512.0.0
  '@coremedia/studio-client.base-models': 2512.0.0
  '@coremedia/studio-client.cap-base-models': 2512.0.0
  '@coremedia/studio-client.cap-rest-client': 2512.0.0
  '@coremedia/studio-client.client-core': 2512.0.0
  '@coremedia/studio-client.ext.cap-base-components': 2512.0.0
  '@coremedia/studio-client.ext.errors-validation-components': 2512.0.0
  '@coremedia/studio-client.ext.eslint-config': 2512.0.0
  '@coremedia/studio-client.ext.form-services-toolkit': 2512.0.0
  '@coremedia/studio-client.ext.library-services-toolkit': 2512.0.0
  '@coremedia/studio-client.ext.link-list-components': 2512.0.0
  '@coremedia/studio-client.ext.ui-components': 2512.0.0
  '@coremedia/studio-client.link-list-models': 2512.0.0
  '@coremedia/studio-client.main.editor-components': 2512.0.0
  '@coremedia/studio-client.multi-site-models': 2512.0.0
  '@jangaroo/build': ^3.4.1
  '@jangaroo/core': ^3.4.1
  '@jangaroo/ext-ts': ^2.1.0
  '@jangaroo/joounit': ^3.4.1
  '@jangaroo/run': ^3.4.1
  '@jangaroo/runtime': ^3.4.1
  eslint: ^9.39.2
  rimraf: ^6.1.2
  rxjs: ^7.8.1
catalogMode: prefer